---
hero_image: images / about-me.png
theme: апельсин
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, дизайн-0, програмування-1, phys-comp-0, виробництво-0, спільноти-0
title: Про мене
description: Використовуйте мову програмування Python для створення фотографій з тексту
original_url: https://codeclubprojects.org/en-GB/python/about-me
interests: ''
technologies: python
site_areas: проекти
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Вступ
  - 
    title: Що вам знадобиться
  - 
    title: Говорячи привіт
  - 
    title: 'Виклик: що у вас на увазі?'
  - 
    title: ASCII art
  - 
    title: 'Виклик: про себе'
  - 
    title: 2025 рік
  - 
    title: 'Виклик: ваш вік у собачих літах'
  - 
    title: 'Виклик: обчислення тексту'
