---
hero_image: afbeeldingen / over-mij.png
theme: oranje
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: maker, ontwerp-0, programmeren-1, phys-comp-0, fabricage-0, gemeeschap-0
title: Over mij
description: Gebruik de programmeertaal Python om afbeeldingen van tekst te maken
original_url: https://codeclubprojects.org/en-GB/python/about-me
interests: ''
technologies: python
site_areas: codeclub, python
steps:
  - 
    title: Introductie
  - 
    title: Wat je nodig hebt
  - 
    title: Hallo zeggen
  - 
    title: 'Uitdaging: waar denk je aan?'
  - 
    title: ASCII-kunst
  - 
    title: 'Uitdaging: over jezelf'
  - 
    title: Het jaar 2025
  - 
    title: 'Uitdaging: je leeftijd in hondenjaren'
  - 
    title: 'Uitdaging: rekenen met tekst'
