---
hero_image: images/about-me.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: O meni
description: Koristi programski jezik Python za kreiranje slika od teksta
original_url: https://codeclubprojects.org/en-GB/python/about-me
interests: ''
technologies: python
site_areas: codeclub, python
steps:
  - 
    title: Uvod
  - 
    title: Trebat će ti
  - 
    title: Reci bok
  - 
    title: 'Izazov: što ti je na umu?'
  - 
    title: ASCII umjetnost
  - 
    title: 'Izazov: o tebi'
  - 
    title: 2025. godina
  - 
    title: 'Izazov: koliko imaš psećih godina?'
  - 
    title: 'Izazov: izračunaj tekst'
