---
hero_image: Bilder/über-mich.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: Schöpfer, Design-0, Programmierung-1, Phys-Comp-0, Herstellung-0, Gemeinde-0
title: Über Mich
description: Schreibe über dich und erstelle Bilder von dir
original_url: https://projects.raspberrypi.org/en/projects/about-me
interests: ''
technologies: Python
site_areas: Codeclub, Python
steps:
  - 
    title: Einführung
  - 
    title: Hallo sagen
  - 
    title: 'Aufgabe: An was denkst du?'
  - 
    title: ASCII Bild
  - 
    title: 'Aufgabe: Über Dich'
  - 
    title: Das Jahr 2025
  - 
    title: 'Aufgabe: Alter in Hundejahren'
  - 
    title: 'Aufgabe: Text berechnen'
  - 
    title: 'Challenge: Einen Text berechnen'
