hero_image: images/about-me.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: À propos de moi
description: Écris et crée des images à propos de toi
original_url: https://projects.raspberrypi.org/en/projects/about-me
interests: ''
technologies: python
site_areas: codeclub, python
steps:
- title: Dire Bonjour
- title: "Défi: Qu'est-ce qui te passe par la tête?"
- title: Art ASCII
- title: "Défi: À propos de toi"
- title: L'an 2025
- title: "Défi: Ton âge en années de chien"
- title: "Défi: calculer du text"
